#!/usr/bin/env python3
"""Dependency license audit.

Scans every Go module linked into the backend and every production npm
package shipped with the web UI, classifies its license, writes
docs/THIRD_PARTY_LICENSES.md and exits non-zero if a copyleft (GPL/AGPL/
LGPL/SSPL/EUPL/MPL is reported for review) or unidentified license is found.

Usage: python3 scripts/license-audit.py [--write]
"""
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKEND = os.path.join(ROOT, "backend")
FRONTEND = os.path.join(ROOT, "frontend")

ALLOWED = {"MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "0BSD", "BlueOak-1.0.0", "Unlicense", "CC0-1.0", "Python-2.0"}
BLOCKED = re.compile(r"\b(A?GPL|LGPL|SSPL|EUPL|Commons Clause|BUSL)\b", re.I)
REVIEW = re.compile(r"\b(MPL|CDDL|EPL)\b", re.I)

SIGNATURES = [
    ("Apache-2.0", r"Apache License,?\s+Version 2\.0"),
    ("MIT", r"Permission is hereby granted, free of charge"),
    ("BSD-3-Clause", r"Neither the name of|may not be used to endorse or promote"),
    ("BSD-2-Clause", r"Redistributions in binary form must reproduce"),
    ("ISC", r"Permission to use, copy, modify, and(/or)? distribute this software for any purpose"),
    ("MPL-2.0", r"Mozilla Public License"),
    ("GPL", r"GNU GENERAL PUBLIC LICENSE"),
    ("LGPL", r"GNU LESSER GENERAL PUBLIC LICENSE"),
]


def classify_text(text):
    for name, pat in SIGNATURES:
        if re.search(pat, text, re.I):
            # BSD-2 text is a subset of BSD-3; prefer the more specific match order above
            return name
    return "UNKNOWN"


def go_modules():
    env = dict(os.environ, GOFLAGS="-mod=mod")
    out = subprocess.run(["go", "list", "-deps", "-f", "{{if .Module}}{{.Module.Path}}\t{{.Module.Version}}\t{{.Module.Dir}}{{end}}", "./..."],
                         cwd=BACKEND, capture_output=True, text=True, env=env, check=True).stdout
    mods = {}
    for line in out.splitlines():
        parts = line.split("\t")
        if len(parts) != 3 or parts[0].startswith("github.com/Eirahoutmoss/"):
            continue
        mods[parts[0]] = (parts[1], parts[2])
    res = []
    for path, (ver, d) in sorted(mods.items()):
        lic = "UNKNOWN"
        for name in ("LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING", "LICENCE"):
            p = os.path.join(d, name)
            if os.path.exists(p):
                lic = classify_text(open(p, errors="ignore").read())
                break
        res.append(("go", path, ver, lic))
    return res


def npm_packages():
    out = subprocess.run(["npm", "ls", "--omit=dev", "--all", "--json"], cwd=FRONTEND, capture_output=True, text=True).stdout
    tree = json.loads(out or "{}")
    seen = {}

    def walk(deps):
        for name, info in (deps or {}).items():
            if "version" not in info or info.get("missing"):
                continue  # optional peer dependency that is not installed
            ver = info["version"]
            key = f"{name}@{ver}"
            if key not in seen:
                pj = os.path.join(FRONTEND, "node_modules", name, "package.json")
                lic = "UNKNOWN"
                if os.path.exists(pj):
                    meta = json.load(open(pj))
                    l = meta.get("license")
                    if isinstance(l, dict):
                        l = l.get("type")
                    if isinstance(meta.get("licenses"), list) and not l:
                        l = " OR ".join(x.get("type", "") for x in meta["licenses"])
                    lic = l or "UNKNOWN"
                seen[key] = ("npm", name, ver, lic)
            walk(info.get("dependencies"))

    walk(tree.get("dependencies"))
    return sorted(seen.values(), key=lambda x: x[1])


def verdict(lic):
    if BLOCKED.search(lic):
        return "BLOCKED"
    if REVIEW.search(lic):
        return "REVIEW"
    parts = [p.strip("() ") for p in re.split(r"\s+(?:OR|AND)\s+", lic)]
    if all(p in ALLOWED for p in parts):
        return "ok"
    if " OR " in lic and any(p in ALLOWED for p in parts):
        return "ok"
    return "UNKNOWN"


def main():
    rows = go_modules() + npm_packages()
    problems = [(r, verdict(r[3])) for r in rows if verdict(r[3]) != "ok"]
    lines = ["# Third-party licenses", "",
             "Generated by `scripts/license-audit.py`. Nexus itself is licensed under Apache-2.0.", "",
             "Policy: permissive licenses (MIT, BSD, ISC, Apache-2.0) are accepted. GPL/AGPL/LGPL/SSPL",
             "dependencies are rejected; MPL/EPL/CDDL require explicit review.", "",
             "## Bundled data", "",
             "- IEEE MA-L (OUI) registry, packaged by [oui-data](https://github.com/silverwind/oui-data) (BSD-2-Clause),",
             "  embedded as `backend/internal/oui/oui.txt.gz`. It can be replaced at runtime with the official IEEE `oui.csv`",
             "  via `NEXUS_OUI_FILE`.", "",
             "## Dependencies", "", "| Ecosystem | Package | Version | License | Status |", "|---|---|---|---|---|"]
    for eco, name, ver, lic in rows:
        lines.append(f"| {eco} | {name} | {ver} | {lic} | {verdict(lic)} |")
    lines.append("")
    lines += [
        "## Windows installer: bundled binaries",
        "",
        "The Windows installer additionally ships the unmodified PostgreSQL 16 server binaries and",
        "the libraries they load (PostgreSQL License, ICU/Unicode, OpenSSL/Apache-2.0, zlib, MIT,",
        "BSD, LGPL-2.1 for GNU gettext's libintl and GNU libiconv as separate DLLs) and the",
        "Microsoft Visual C++ runtime DLLs (Microsoft redistributable code). Their license texts",
        "are installed in `licenses\\` next to `nexus.exe`; the list is in",
        "[deployments/windows/licenses/BUNDLED.txt](../deployments/windows/licenses/BUNDLED.txt).",
        "Versions and checksums are pinned in `deployments/windows/deps.env`.",
        "",
    ]
    if "--write" in sys.argv:
        with open(os.path.join(ROOT, "docs", "THIRD_PARTY_LICENSES.md"), "w") as f:
            f.write("\n".join(lines))
    print(f"{len(rows)} dependencies scanned ({sum(1 for r in rows if r[0]=='go')} Go, {sum(1 for r in rows if r[0]=='npm')} npm)")
    for (eco, name, ver, lic), v in problems:
        print(f"  {v}: {eco} {name}@{ver} — {lic}")
    if problems:
        sys.exit(1)
    print("license audit passed")


if __name__ == "__main__":
    main()
